### ISSUE TITLE
 Make guide outlines in the Dictionary expand/collapse with repeated clicks

### ISSUE THREAD

**Issue by macMikey** [livecode/this-week-in-livecode#4]
For me, the thing that fixed it was updating
Contents->Tools->Documentation->html_viewer->bootstrap.min.css
and
Contents->Tools->Documentation->html_viewer->css->bootstrap.min.css
to v. 3.3.7.

The current version of Bootstrap is at https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip

Before I toss in a pull request for this, someone else should also test it, IMHO.

**Comment by peter-b** [comment]
@macMikey This is not the git repository you're looking for... I think you want https://github.com/livecode/livecode

**Comment by macMikey** [comment]
I was commenting because this was from the "this week" newsletter.  Moving...

**Comment by peter-b** [comment]
@macMikey Why not comment on the _already open bug report_ that was _linked in the newsletter_!?!?

**Comment by macMikey** [comment]
uhhhhh, because I missed it?  So adding the issues I added in livecode/livecode wasn't the way to go, either?
