### ISSUE TITLE
Reduce whitespace in Dictionary

### ISSUE THREAD

**Issue by macMikey** [livecode/this-week-in-livecode#5]
IMHO, the best way to fix this is to re-engineer the documentation/dictionary.  I would get rid of the monolithic dictionary pane, and replace it with several smaller panes, whose dimensions are dictated by the GM.  The panes would be
lcdoc_library_chooser (the popup)
lcdoc_list (the panel below on the left)
table_list (top right panel)
lcdoc_body (bottom right)

But, someone has to at least say "we're game" before I'm going to work on it.

**Comment by peter-b** [comment]
@macMikey This bug tracker is for issues with the newsletter.  For issues with LiveCode itself, please add a ticket to http://quality.livecode.com/.
