### ISSUE TITLE
Typo in link for second 'want to help?' suggestion

### ISSUE THREAD

**Issue by presstoexit** [livecode/this-week-in-livecode#9]
The link to the 'default script for scrollbars' QC report should be to #17851, not #17975 (BTW I tried to fix this directly and make a pull request, but got into permission issues with git...; also tried to do it directly in GitHub web interface following https://github.com/livecode/livecode/blob/community-docs/docs/contributing_to_docs.md but failed there also.)

**Comment by peter-b** [comment]
Hi @presstoexit, thanks for the report, I'll go ahead and fix it.
